create database KNOOCK

use KNOOCK

CREATE TABLE Tipo (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Tipo NVARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Usuario (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nome NVARCHAR(100) NOT NULL,
Telefone NVARCHAR(15) NOT NULL,
Email NVARCHAR(100) NOT NULL UNIQUE,
Data_Nascimento DATE,
Endereco NVARCHAR(255),
Senha NVARCHAR(255) NOT NULL,
Codigo_Recuperacao NVARCHAR(10)
);

CREATE TABLE Tipo_Usuario (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Id_Usuario UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Usuario(ID),
Id_Tipo UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tipo(ID)
);

CREATE TABLE Afiliado (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TipoUsuario_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tipo_Usuario(ID),
KnookCoins INT NOT NULL DEFAULT 0
);

CREATE TABLE Condomino (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TipoUsuario_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tipo_Usuario(ID),
DeliveryPin NVARCHAR(10),
PIN NVARCHAR(6),
Bloco NVARCHAR(5),
Apartamento NVARCHAR(10)
);

CREATE TABLE Veiculo (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TipoUsuario_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tipo_Usuario(ID),
Marca NVARCHAR(50),
Modelo NVARCHAR(50),
Placa NVARCHAR(10),
Ano INT
);

CREATE TABLE Entrega (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TipoUsuario_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tipo_Usuario(ID),
Veiculo_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Veiculo(ID),
Data_Registro DATETIME,
Status NVARCHAR(10) NOT NULL,
Foto_Produto NVARCHAR(255),
Notificacao_Morador BIT DEFAULT 0,
PIN_Retirada NVARCHAR(10),
Data_Retirada DATETIME,

FG_entrega bit,
Data_Notificacao DATETIME
);

CREATE TABLE Notificacao (
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TipoUsuario_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tipo_Usuario(ID),
Mensagem NVARCHAR(255),
Data_Notificacao DATETIME,
Status NVARCHAR(20),
Tipo NVARCHAR(20),
Imagem_Aviso TEXT
);

CREATE TABLE Notificacao_Entrega (
Notificacao_ID UNIQUEIDENTIFIER PRIMARY KEY FOREIGN KEY REFERENCES Notificacao(ID),
Entrega_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Entrega(ID)
);



INSERT INTO dbo.Tipo (tipo)
VALUES 
    ('Administrador'),
    ('Condomino'),
    ('Porteiro'),
    ('Afiliado');


SELECT * FROM dbo.TIPO